# Development stage
FROM node:22-alpine as dev

WORKDIR /app

COPY backend/package.json ./

RUN npm install

COPY backend/ .

CMD ["npx", "nodemon", "index.js"]


# Production stage
FROM node:22-alpine as prod

WORKDIR /app

COPY backend/package.json ./

RUN npm install

COPY backend/ .

CMD ["node", "index.js"]