# Development stage
FROM node:22-alpine as dev

WORKDIR /app

COPY frontend/package.json ./

RUN npm install

COPY frontend/ .

CMD ["npm", "start"]


# Build stage
FROM node:22-alpine as build

WORKDIR /app

COPY frontend/package.json ./

RUN npm install

COPY frontend/ .

RUN npm run build


# Production stage
FROM nginx:alpine as prod

COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]